version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cinema_reservation_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  discovery-service:
    build:
      context: services/discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  user-service:
    build:
      context: services/user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service

  movie-service:
    build:
      context: services/movie-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service
      -
  payment-service:
    build:
      context: services/payment-service
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - discovery-service

  reservation-service:
    build:
      context: services/reservation-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - discovery-service

volumes:
  postgres-data: