services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  discovery-service:
    image: pwr260654/cinema-discovery-service
    build:
      context: services/discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - kafka
    develop:
      watch:
        - action: rebuild
          path: services/discovery-service

  api-gateway:
    image: pwr260654/cinema-api-gateway
    build:
      context: services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka
      BOOTSTRAP_SERVERS_URL: kafka:9092
    depends_on:
      - discovery-service
    develop:
      watch:
        - action: rebuild
          path: services/api-gateway

  movie-service:
    image: pwr260654/cinema-movie-service
    build:
      context: services/movie-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka
      BOOTSTRAP_SERVERS_URL: kafka:9092
    depends_on:
      - api-gateway
    develop:
      watch:
        - action: rebuild
          path: services/movie-service

  reservation-service:
    image: pwr260654/cinema-reservation-service
    build:
      context: services/reservation-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka
      BOOTSTRAP_SERVERS_URL: kafka:9092
      MOVIE_SERVICE_URL: http://movie-service:8081
    depends_on:
      - api-gateway
    develop:
      watch:
        - action: rebuild
          path: services/reservation-service

  payment-service:
    image: pwr260654/cinema-payment-service
    build:
      context: services/payment-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka
      BOOTSTRAP_SERVERS_URL: kafka:9092
    depends_on:
      - api-gateway
    develop:
      watch:
        - action: rebuild
          path: services/payment-service

  ticket-service:
    image: pwr260654/cinema-ticket-service
    build:
      context: services/ticket-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka
      BOOTSTRAP_SERVERS_URL: kafka:9092
    depends_on:
      - api-gateway
    develop:
      watch:
        - action: rebuild
          path: services/ticket-service

  notification-service:
    image: pwr260654/cinema-notification-service
    build:
      context: services/notification-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka
      BOOTSTRAP_SERVERS_URL: kafka:9092
    depends_on:
      - api-gateway
    develop:
      watch:
        - action: rebuild
          path: services/notification-service

# docker compose up zookeeper kafka
# docker compose logs -f -t
