version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  discovery-service:
    image: pwr260654/cinema-discovery-service
    ports:
      - "8761:8761"
    depends_on:
      - kafka

  api-gateway:
    image: pwr260654/cinema-api-gateway
    ports:
      - "8080:8080"
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka
      BOOTSTRAP_SERVERS_URL: kafka:9092
    depends_on:
      - discovery-service

  movie-service:
    image: pwr260654/cinema-movie-service
    ports:
      - "8081:8081"
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka
      BOOTSTRAP_SERVERS_URL: kafka:9092
    depends_on:
      - api-gateway

  reservation-service:
    image: pwr260654/cinema-reservation-service
    ports:
      - "8082:8082"
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka
      BOOTSTRAP_SERVERS_URL: kafka:9092
      MOVIE_SERVICE_URL: http://movie-service:8081
    depends_on:
      - api-gateway

  payment-service:
    image: pwr260654/cinema-payment-service
    ports:
      - "8083:8083"
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka
      BOOTSTRAP_SERVERS_URL: kafka:9092
    depends_on:
      - api-gateway

  ticket-service:
    image: pwr260654/cinema-ticket-service
    ports:
      - "8084:8084"
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka
      BOOTSTRAP_SERVERS_URL: kafka:9092
    depends_on:
      - api-gateway

  notification-service:
    image: pwr260654/cinema-notification-service
    ports:
      - "8085:8085"
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka
      BOOTSTRAP_SERVERS_URL: kafka:9092
    depends_on:
      - api-gateway

# docker build -t pwr260654/cinema-discovery-service:latest .\services\discovery-service\
# docker build -t pwr260654/cinema-api-gateway:latest .\services\api-gateway\
# docker build -t pwr260654/cinema-movie-service:latest .\services\movie-service\
# docker build -t pwr260654/cinema-notification-service:latest .\services\notification-service\
# docker build -t pwr260654/cinema-payment-service:latest .\services\payment-service\
# docker build -t pwr260654/cinema-reservation-service:latest .\services\reservation-service\
# docker build -t pwr260654/cinema-ticket-service:latest .\services\ticket-service\

# docker push <tag>

# docker compose up zookeeper kafka
# docker compose logs -f -t
