server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      forwarded:
        enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: [ "GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH", "HEAD" ]
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: api-gateway
        url: /v3/api-docs
      - name: movie-service
        url: /api/movies/v3/api-docs
      - name: reservation-service
        url: /api/reservations/v3/api-docs
      - name: ticket-service
        url: /api/tickets/v3/api-docs
      - name: payment-service
        url: /api/payments/v3/api-docs
